---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.7
  - name: ubuntu-16.04
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[vsftpd::default]
    attributes:
