settings:
  parallel: true

driver:
  name: docker

platforms:
- name: centos-6
  driver:
    image: centos:6
    platform: rhel

- name: debian-stable
  driver:
    image: debian:stable
    platform: debian
    provision_command:
      - /usr/bin/apt-get update
      - /usr/bin/apt-get install -y net-tools

- name: ubuntu-18.04
  driver:
    image: ubuntu-upstart:14.04
    platform: ubuntu
    provision_command:
      - /usr/bin/apt-get update
      - /usr/bin/apt-get install -y net-tools

provisioner:
  name: chef_zero
  chef_license: accept

suites:
  - name: default
    run_list:
      - recipe[vsftpd::default]
